CREATE TABLE TYPETEST (
  TYPE_1 BIGINT NOT NULL  COMMENT 'タイプ１',
  TYPE_2 BOOL NOT NULL  COMMENT 'タイプ２',
  TYPE_3 CHAR(8) NOT NULL  COMMENT 'タイプ３',
  TYPE_4 DATETIME NOT NULL  COMMENT 'タイプ４',
  TYPE_5 DATE NULL DEFAULT NULL  COMMENT 'タイプ５',
  TYPE_6 DECIMAL(10,2) NULL DEFAULT NULL  COMMENT 'タイプ６',
  TYPE_7 INT(10) NULL DEFAULT NULL  COMMENT 'タイプ７',
  TYPE_8 TIMESTAMP NULL DEFAULT NULL  COMMENT 'タイプ８',
  TYPE_9 VARCHAR(20) NULL DEFAULT NULL  COMMENT 'タイプ９',
  TYPE_10 BLOB NULL DEFAULT NULL  COMMENT 'タイプ１０'
)
COMMENT='タイプテスト'