CREATE TABLE BANK_DATA_RECORD (
  DATA_RECORD_ID NUMERIC(9) NOT NULL,
  RECEIVING_BANK_NUMBER CHAR(4),
  RECEIVING_BRANCH_NUMBER CHAR(3),
  DEPOSIT_TYPE CHAR(1),
  ACCOUNT_NUMBER CHAR(7),
  RECIPIENT_NAME CHAR(30),
  TRANSFER_AMOUNT NUMERIC(10),
  HEADER_RECORD_ID NUMERIC(9) NOT NULL,
  PRIMARY KEY (DATA_RECORD_ID)
);
COMMENT ON table BANK_DATA_RECORD is '銀行データレコード';
COMMENT ON column BANK_DATA_RECORD.DATA_RECORD_ID is 'データID';
COMMENT ON column BANK_DATA_RECORD.RECEIVING_BANK_NUMBER is '被仕向金融機関番号';
COMMENT ON column BANK_DATA_RECORD.RECEIVING_BRANCH_NUMBER is '被仕向支店番号';
COMMENT ON column BANK_DATA_RECORD.DEPOSIT_TYPE is '預金種目';
COMMENT ON column BANK_DATA_RECORD.ACCOUNT_NUMBER is '口座番号';
COMMENT ON column BANK_DATA_RECORD.RECIPIENT_NAME is '受取人名';
COMMENT ON column BANK_DATA_RECORD.TRANSFER_AMOUNT is '振込金額';
COMMENT ON column BANK_DATA_RECORD.HEADER_RECORD_ID is 'ヘッダID';
CREATE SEQUENCE DATA_RECORD_ID_SEQ increment by 1 start with 1;
