CREATE TABLE UGROUP (
  UGROUP_ID NUMERIC(9) NOT NULL,
  UGROUP_NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (UGROUP_ID)
);
COMMENT ON table UGROUP is 'グループ';
COMMENT ON column UGROUP.UGROUP_ID is 'グループID';
COMMENT ON column UGROUP.UGROUP_NAME is 'グループ名';
CREATE SEQUENCE UGROUP_ID_SEQ increment by 1 start with 1;
