CREATE TABLE INDUSTRY (
  INDUSTRY_CODE CHAR(2) NOT NULL,
  INDUSTRY_NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (INDUSTRY_CODE)
);
COMMENT ON table INDUSTRY is '業種';
COMMENT ON column INDUSTRY.INDUSTRY_CODE is '業種コード';
COMMENT ON column INDUSTRY.INDUSTRY_NAME is '業種名';
