CREATE TABLE PASSWORD_HISTORY (
  PASSWORD_HISTORY_ID NUMERIC(15) NOT NULL,
  USER_ID NUMERIC(9) NOT NULL,
  USER_PASSWORD VARCHAR(44) NOT NULL,
  PRIMARY KEY (PASSWORD_HISTORY_ID)
);
COMMENT ON table PASSWORD_HISTORY is 'パスワード変更履歴';
COMMENT ON column PASSWORD_HISTORY.PASSWORD_HISTORY_ID is 'パスワード履歴';
COMMENT ON column PASSWORD_HISTORY.USER_ID is 'ユーザID';
COMMENT ON column PASSWORD_HISTORY.USER_PASSWORD is 'パスワード';
CREATE SEQUENCE PASSWORD_HISTORY_ID_SEQ increment by 1 start with 1;
