CREATE TABLE PERMISSION_UNIT_REQUEST (
  PERMISSION_UNIT_ID NUMERIC(9) NOT NULL,
  REQUEST_ID VARCHAR(2000) NOT NULL,
  PRIMARY KEY (PERMISSION_UNIT_ID, REQUEST_ID)
);
COMMENT ON table PERMISSION_UNIT_REQUEST is '認可単位リクエスト';
COMMENT ON column PERMISSION_UNIT_REQUEST.PERMISSION_UNIT_ID is '認可単位ID';
COMMENT ON column PERMISSION_UNIT_REQUEST.REQUEST_ID is 'リクエストID';
