CREATE TABLE BUSINESS_DATE (
  SEGMENT_ID CHAR(2) NOT NULL,
  BIZ_DATE DATE NOT NULL,
  PRIMARY KEY (SEGMENT_ID)
);
COMMENT ON table BUSINESS_DATE is '業務日付';
COMMENT ON column BUSINESS_DATE.SEGMENT_ID is '業務日付区分';
COMMENT ON column BUSINESS_DATE.BIZ_DATE is '日付';
