CREATE TABLE ZIP_CODE_DATA_ERROR (
  LINE_NUMBER NUMERIC(18) NOT NULL,
  LOCAL_GOVERNMENT_CODE VARCHAR(2000),
  ZIP_CODE_5DIGIT VARCHAR(2000),
  ZIP_CODE_7DIGIT VARCHAR(2000),
  PREFECTURE_KANA VARCHAR(2000),
  CITY_KANA VARCHAR(2000),
  ADDRESS_KANA VARCHAR(2000),
  PREFECTURE_KANJI VARCHAR(2000),
  CITY_KANJI VARCHAR(2000),
  ADDRESS_KANJI VARCHAR(2000),
  MULTIPLE_ZIP_CODES VARCHAR(2000),
  NUMBERED_EVERY_KOAZA VARCHAR(2000),
  ADDRESS_WITH_CHOME VARCHAR(2000),
  MULTIPLE_ADDRESS VARCHAR(2000),
  UPDATE_DATA VARCHAR(2000),
  UPDATE_DATA_REASON VARCHAR(2000),
  PRIMARY KEY (LINE_NUMBER)
);
COMMENT ON table ZIP_CODE_DATA_ERROR is '郵便番号データ_エラー';
COMMENT ON column ZIP_CODE_DATA_ERROR.LINE_NUMBER is '行番号';
COMMENT ON column ZIP_CODE_DATA_ERROR.LOCAL_GOVERNMENT_CODE is '全国地方公共団体コード';
COMMENT ON column ZIP_CODE_DATA_ERROR.ZIP_CODE_5DIGIT is '郵便番号（5桁）';
COMMENT ON column ZIP_CODE_DATA_ERROR.ZIP_CODE_7DIGIT is '郵便番号（7桁）';
COMMENT ON column ZIP_CODE_DATA_ERROR.PREFECTURE_KANA is '都道府県名カナ';
COMMENT ON column ZIP_CODE_DATA_ERROR.CITY_KANA is '市区町村名カナ';
COMMENT ON column ZIP_CODE_DATA_ERROR.ADDRESS_KANA is '町域名カナ';
COMMENT ON column ZIP_CODE_DATA_ERROR.PREFECTURE_KANJI is '都道府県名漢字';
COMMENT ON column ZIP_CODE_DATA_ERROR.CITY_KANJI is '市区町村名漢字';
COMMENT ON column ZIP_CODE_DATA_ERROR.ADDRESS_KANJI is '町域名漢字';
COMMENT ON column ZIP_CODE_DATA_ERROR.MULTIPLE_ZIP_CODES is '一町域が二以上の郵便番号';
COMMENT ON column ZIP_CODE_DATA_ERROR.NUMBERED_EVERY_KOAZA is '小字毎に番地が起番されている町域';
COMMENT ON column ZIP_CODE_DATA_ERROR.ADDRESS_WITH_CHOME is '丁目を有する町域';
COMMENT ON column ZIP_CODE_DATA_ERROR.MULTIPLE_ADDRESS is '一つの郵便番号で二以上の町域';
COMMENT ON column ZIP_CODE_DATA_ERROR.UPDATE_DATA is '更新';
COMMENT ON column ZIP_CODE_DATA_ERROR.UPDATE_DATA_REASON is '変更理由';
