CREATE TABLE PERMISSION_UNIT (
  PERMISSION_UNIT_ID NUMERIC(9) NOT NULL,
  PERMISSION_UNIT_NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (PERMISSION_UNIT_ID)
);
COMMENT ON table PERMISSION_UNIT is '認可単位';
COMMENT ON column PERMISSION_UNIT.PERMISSION_UNIT_ID is '認可単位ID';
COMMENT ON column PERMISSION_UNIT.PERMISSION_UNIT_NAME is '認可単位名';
CREATE SEQUENCE PERMISSION_UNIT_ID_SEQ increment by 1 start with 1;
