CREATE TABLE BANK_HEADER_RECORD (
  HEADER_RECORD_ID NUMERIC(9) NOT NULL,
  SENDING_BANK_NUMBER CHAR(4),
  SENDING_BRANCH_NUMBER CHAR(3),
  DEPOSIT_TYPE_CLIENT CHAR(1),
  ACCOUNT_NUMBER_CLIENT CHAR(7),
  PRIMARY KEY (HEADER_RECORD_ID)
);
COMMENT ON table BANK_HEADER_RECORD is '銀行ヘッダレコード';
COMMENT ON column BANK_HEADER_RECORD.HEADER_RECORD_ID is 'ヘッダID';
COMMENT ON column BANK_HEADER_RECORD.SENDING_BANK_NUMBER is '仕向金融機関番号';
COMMENT ON column BANK_HEADER_RECORD.SENDING_BRANCH_NUMBER is '仕向支店番号';
COMMENT ON column BANK_HEADER_RECORD.DEPOSIT_TYPE_CLIENT is '預金種目(依頼人)';
COMMENT ON column BANK_HEADER_RECORD.ACCOUNT_NUMBER_CLIENT is '口座番号(依頼人)';
CREATE SEQUENCE HEADER_RECORD_ID_SEQ increment by 1 start with 1;
