CREATE TABLE CLIENT (
  CLIENT_ID NUMERIC(9) NOT NULL,
  CLIENT_NAME VARCHAR(128) NOT NULL,
  INDUSTRY_CODE CHAR(2),
  PRIMARY KEY (CLIENT_ID)
);
COMMENT ON table CLIENT is '顧客';
COMMENT ON column CLIENT.CLIENT_ID is '顧客ID';
COMMENT ON column CLIENT.CLIENT_NAME is '顧客名';
COMMENT ON column CLIENT.INDUSTRY_CODE is '業種コード';
CREATE SEQUENCE CLIENT_ID_SEQ increment by 1 start with 1;
