CREATE TABLE SYSTEM_ACCOUNT (
  USER_ID NUMERIC(9) NOT NULL,
  LOGIN_ID VARCHAR(20) NOT NULL,
  USER_PASSWORD VARCHAR(44) NOT NULL,
  USER_ID_LOCKED NUMERIC(1) NOT NULL,
  PASSWORD_EXPIRATION_DATE DATE NOT NULL,
  FAILED_COUNT NUMERIC(2) NOT NULL,
  EFFECTIVE_DATE_FROM DATE,
  EFFECTIVE_DATE_TO DATE,
  LAST_LOGIN_DATE_TIME TIMESTAMP(6),
  VERSION NUMERIC(10) NOT NULL DEFAULT 1,
  PRIMARY KEY (USER_ID)
);
COMMENT ON table SYSTEM_ACCOUNT is 'システムアカウント';
COMMENT ON column SYSTEM_ACCOUNT.USER_ID is 'ユーザID';
COMMENT ON column SYSTEM_ACCOUNT.LOGIN_ID is 'ログインID';
COMMENT ON column SYSTEM_ACCOUNT.USER_PASSWORD is 'パスワード';
COMMENT ON column SYSTEM_ACCOUNT.USER_ID_LOCKED is 'ユーザIDロック';
COMMENT ON column SYSTEM_ACCOUNT.PASSWORD_EXPIRATION_DATE is 'パスワード有効期限';
COMMENT ON column SYSTEM_ACCOUNT.FAILED_COUNT is '認証失敗回数';
COMMENT ON column SYSTEM_ACCOUNT.EFFECTIVE_DATE_FROM is '有効期限(FROM)';
COMMENT ON column SYSTEM_ACCOUNT.EFFECTIVE_DATE_TO is '有効期限(TO)';
COMMENT ON column SYSTEM_ACCOUNT.LAST_LOGIN_DATE_TIME is '最終ログイン日時';
COMMENT ON column SYSTEM_ACCOUNT.VERSION is 'バージョン番号';
CREATE SEQUENCE USER_ID_SEQ increment by 1 start with 1;
