CREATE TABLE TYPETEST (
  TYPE_1 NUMBER(11) NOT NULL ,
  TYPE_3 CHAR(8 CHAR) NOT NULL ,
  TYPE_4 DATE NOT NULL ,
  TYPE_5 NUMBER(10,2),
  TYPE_6 NVARCHAR2(20),
  TYPE_7 VARCHAR2(40 CHAR),
  TYPE_8 NCHAR(10),
  TYPE_9 LONG,
  TYPE_10 BLOB,
  TYPE_11 CLOB
);
COMMENT ON table TYPETEST is 'タイプテスト';
COMMENT ON column TYPETEST.TYPE_1 is 'タイプ１';
COMMENT ON column TYPETEST.TYPE_3 is 'タイプ３';
COMMENT ON column TYPETEST.TYPE_4 is 'タイプ４';
COMMENT ON column TYPETEST.TYPE_5 is 'タイプ５';
COMMENT ON column TYPETEST.TYPE_6 is 'タイプ６';
COMMENT ON column TYPETEST.TYPE_7 is 'タイプ７';
COMMENT ON column TYPETEST.TYPE_8 is 'タイプ８';
COMMENT ON column TYPETEST.TYPE_9 is 'タイプ９';
COMMENT ON column TYPETEST.TYPE_10 is 'タイプ１０';
COMMENT ON column TYPETEST.TYPE_11 is 'タイプ１１';
