CREATE TABLE TYPETEST (
  TYPE_1 BIGINT NOT NULL,
  TYPE_3 CHAR NOT NULL,
  TYPE_4 DATE NOT NULL,
  TYPE_5 INTEGER,
  TYPE_6 VARCHAR(10),
  TYPE_7 NUMERIC(10,2),
  TYPE_8 TIMESTAMP,
  TYPE_9 BLOB(2000),
  TYPE_10 CLOB(1000),
  TYPE_11 DECIMAL(11,3),
  TYPE_12 SMALLINT
);
COMMENT ON table TYPETEST is 'タイプテスト';
COMMENT ON column TYPETEST.TYPE_1 is 'タイプ１';
COMMENT ON column TYPETEST.TYPE_3 is 'タイプ３';
COMMENT ON column TYPETEST.TYPE_4 is 'タイプ４';
COMMENT ON column TYPETEST.TYPE_5 is 'タイプ５';
COMMENT ON column TYPETEST.TYPE_6 is 'タイプ６';
COMMENT ON column TYPETEST.TYPE_7 is 'タイプ７';
COMMENT ON column TYPETEST.TYPE_8 is 'タイプ８';
COMMENT ON column TYPETEST.TYPE_9 is 'タイプ９';
COMMENT ON column TYPETEST.TYPE_10 is 'タイプ１０';
COMMENT ON column TYPETEST.TYPE_11 is 'タイプ１１';
COMMENT ON column TYPETEST.TYPE_12 is 'タイプ１２';
