CREATE TABLE TEST_TBL1 (
  TEST_TBL1_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
  NAME VARCHAR(30)
);
COMMENT ON table TEST_TBL1 is 'テストテーブル1';
COMMENT ON column TEST_TBL1.TEST_TBL1_ID is 'TEST_TBL1_ID';
COMMENT ON column TEST_TBL1.NAME is 'NAME';
