CREATE TABLE gspanother.TEST_TBL4 (
  TEST_TBL4_ID BIGSERIAL NOT NULL,
  SEQTEST_AUTO SERIAL,
  PRIMARY KEY (TEST_TBL4_ID)
);
COMMENT ON table gspanother.TEST_TBL4 is 'テストテーブル4';
COMMENT ON column gspanother.TEST_TBL4.TEST_TBL4_ID is 'TEST_TBL4_ID';
COMMENT ON column gspanother.TEST_TBL4.SEQTEST_AUTO is 'SEQTEST_AUTO';
