CREATE TABLE PUBLIC.TYPETEST (
  TYPE_1 BOOLEAN NOT NULL,
  TYPE_2 BIGINT NOT NULL,
  TYPE_3 DECIMAL NOT NULL,
  TYPE_4 DATE NOT NULL,
  TYPE_5 TIMESTAMP,
  TYPE_6 VARCHAR(20),
  TYPE_7 BYTEA
);
COMMENT ON table PUBLIC.TYPETEST is 'タイプテスト';
COMMENT ON column PUBLIC.TYPETEST.TYPE_1 is 'タイプ１';
COMMENT ON column PUBLIC.TYPETEST.TYPE_2 is 'タイプ２';
COMMENT ON column PUBLIC.TYPETEST.TYPE_3 is 'タイプ３';
COMMENT ON column PUBLIC.TYPETEST.TYPE_4 is 'タイプ４';
COMMENT ON column PUBLIC.TYPETEST.TYPE_5 is 'タイプ５';
COMMENT ON column PUBLIC.TYPETEST.TYPE_6 is 'タイプ６';
COMMENT ON column PUBLIC.TYPETEST.TYPE_7 is 'タイプ７';
