CREATE TABLE CUSTOMERS (
  CUSTOMER_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
  CUSTOMER_NAME VARCHAR(100) NOT NULL,
  MAIL_ADDRESS VARCHAR(100) NOT NULL,
  TEL VARCHAR(15)
);
COMMENT ON table CUSTOMERS is '顧客';
COMMENT ON column CUSTOMERS.CUSTOMER_ID is '顧客ID';
COMMENT ON column CUSTOMERS.CUSTOMER_NAME is '名前';
COMMENT ON column CUSTOMERS.MAIL_ADDRESS is 'メールアドレス';
COMMENT ON column CUSTOMERS.TEL is '電話番号';
