CREATE TABLE ORDER_DETAILS (
  ORDER_DETAIL_ID BIGINT NOT NULL,
  ORDER_ID BIGINT NOT NULL,
  PRODUCT_ID BIGINT NOT NULL
);
COMMENT ON table ORDER_DETAILS is '注文明細';
COMMENT ON column ORDER_DETAILS.ORDER_DETAIL_ID is '明細ID';
COMMENT ON column ORDER_DETAILS.ORDER_ID is '注文ID';
COMMENT ON column ORDER_DETAILS.PRODUCT_ID is '商品ID';
