CREATE TABLE ORDERS (
  ORDER_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
  CUSTOMER_ID BIGINT NOT NULL,
  CUSTOMER_DATE TIMESTAMP
);
COMMENT ON table ORDERS is '注文';
COMMENT ON column ORDERS.ORDER_ID is '注文ID';
COMMENT ON column ORDERS.CUSTOMER_ID is '顧客ID';
COMMENT ON column ORDERS.CUSTOMER_DATE is '注文日時';
