CREATE TABLE TYPETEST (
  TYPE_1 BIGINT NOT NULL,
  TYPE_2 BOOL NOT NULL,
  TYPE_3 CHAR(8) NOT NULL,
  TYPE_4 DATE NOT NULL,
  TYPE_5 NUMERIC(4,2),
  TYPE_6 SERIAL,
  TYPE_7 TEXT,
  TYPE_8 TIMESTAMP,
  TYPE_9 VARCHAR(20),
  TYPE_10 BYTEA
);
COMMENT ON table TYPETEST is 'タイプテスト';
COMMENT ON column TYPETEST.TYPE_1 is 'タイプ１';
COMMENT ON column TYPETEST.TYPE_2 is 'タイプ２';
COMMENT ON column TYPETEST.TYPE_3 is 'タイプ３';
COMMENT ON column TYPETEST.TYPE_4 is 'タイプ４';
COMMENT ON column TYPETEST.TYPE_5 is 'タイプ５';
COMMENT ON column TYPETEST.TYPE_6 is 'タイプ６';
COMMENT ON column TYPETEST.TYPE_7 is 'タイプ７';
COMMENT ON column TYPETEST.TYPE_8 is 'タイプ８';
COMMENT ON column TYPETEST.TYPE_9 is 'タイプ９';
COMMENT ON column TYPETEST.TYPE_10 is 'タイプ１０';
