CREATE TABLE ZIP_CODE_DATA (
  LOCAL_GOVERNMENT_CODE CHAR(5) NOT NULL,
  ZIP_CODE_5DIGIT CHAR(5) NOT NULL,
  ZIP_CODE_7DIGIT CHAR(7) NOT NULL,
  PREFECTURE_KANA VARCHAR(128) NOT NULL,
  CITY_KANA VARCHAR(128) NOT NULL,
  ADDRESS_KANA VARCHAR(128) NOT NULL,
  PREFECTURE_KANJI VARCHAR(128) NOT NULL,
  CITY_KANJI VARCHAR(128) NOT NULL,
  ADDRESS_KANJI VARCHAR(128) NOT NULL,
  MULTIPLE_ZIP_CODES NUMERIC(1) NOT NULL,
  NUMBERED_EVERY_KOAZA NUMERIC(1) NOT NULL,
  ADDRESS_WITH_CHOME NUMERIC(1) NOT NULL,
  MULTIPLE_ADDRESS NUMERIC(1) NOT NULL,
  UPDATE_DATA CHAR(1) NOT NULL,
  UPDATE_DATA_REASON CHAR(1) NOT NULL
);
COMMENT ON table ZIP_CODE_DATA is '郵便番号データ';
COMMENT ON column ZIP_CODE_DATA.LOCAL_GOVERNMENT_CODE is '全国地方公共団体コード';
COMMENT ON column ZIP_CODE_DATA.ZIP_CODE_5DIGIT is '郵便番号（5桁）';
COMMENT ON column ZIP_CODE_DATA.ZIP_CODE_7DIGIT is '郵便番号（7桁）';
COMMENT ON column ZIP_CODE_DATA.PREFECTURE_KANA is '都道府県名カナ';
COMMENT ON column ZIP_CODE_DATA.CITY_KANA is '市区町村名カナ';
COMMENT ON column ZIP_CODE_DATA.ADDRESS_KANA is '町域名カナ';
COMMENT ON column ZIP_CODE_DATA.PREFECTURE_KANJI is '都道府県名漢字';
COMMENT ON column ZIP_CODE_DATA.CITY_KANJI is '市区町村名漢字';
COMMENT ON column ZIP_CODE_DATA.ADDRESS_KANJI is '町域名漢字';
COMMENT ON column ZIP_CODE_DATA.MULTIPLE_ZIP_CODES is '一町域が二以上の郵便番号';
COMMENT ON column ZIP_CODE_DATA.NUMBERED_EVERY_KOAZA is '小字毎に番地が起番されている町域';
COMMENT ON column ZIP_CODE_DATA.ADDRESS_WITH_CHOME is '丁目を有する町域';
COMMENT ON column ZIP_CODE_DATA.MULTIPLE_ADDRESS is '一つの郵便番号で二以上の町域';
COMMENT ON column ZIP_CODE_DATA.UPDATE_DATA is '更新';
COMMENT ON column ZIP_CODE_DATA.UPDATE_DATA_REASON is '変更理由';
