CREATE TABLE USERS (
  USER_ID NUMERIC(9) NOT NULL,
  KANJI_NAME VARCHAR(128) NOT NULL,
  KANA_NAME VARCHAR(128) NOT NULL,
  PRIMARY KEY (USER_ID)
);
COMMENT ON table USERS is 'ユーザ';
COMMENT ON column USERS.USER_ID is 'ユーザID';
COMMENT ON column USERS.KANJI_NAME is '漢字氏名';
COMMENT ON column USERS.KANA_NAME is 'ふりがな';
