CREATE TABLE UGROUP_AUTHORITY (
  UGROUP_ID NUMERIC(9) NOT NULL,
  PERMISSION_UNIT_ID NUMERIC(9) NOT NULL,
  PRIMARY KEY (UGROUP_ID, PERMISSION_UNIT_ID)
);
COMMENT ON table UGROUP_AUTHORITY is 'グループ権限';
COMMENT ON column UGROUP_AUTHORITY.UGROUP_ID is 'グループID';
COMMENT ON column UGROUP_AUTHORITY.PERMISSION_UNIT_ID is '認可単位ID';
