CREATE TABLE UGROUP_SYSTEM_ACCOUNT (
  UGROUP_ID NUMERIC(9) NOT NULL,
  USER_ID NUMERIC(9) NOT NULL,
  EFFECTIVE_DATE_FROM DATE NOT NULL,
  EFFECTIVE_DATE_TO DATE,
  PRIMARY KEY (UGROUP_ID, USER_ID, EFFECTIVE_DATE_FROM)
);
COMMENT ON table UGROUP_SYSTEM_ACCOUNT is 'グループシステムアカウント';
COMMENT ON column UGROUP_SYSTEM_ACCOUNT.UGROUP_ID is 'グループID';
COMMENT ON column UGROUP_SYSTEM_ACCOUNT.USER_ID is 'ユーザID';
COMMENT ON column UGROUP_SYSTEM_ACCOUNT.EFFECTIVE_DATE_FROM is '有効日(FROM)';
COMMENT ON column UGROUP_SYSTEM_ACCOUNT.EFFECTIVE_DATE_TO is '有効日(TO)';
