CREATE TABLE TYPETEST (
  TYPE_1 BIGINT NOT NULL,
  TYPE_2 BOOL NOT NULL,
  TYPE_3 CHAR(8) NOT NULL,
  TYPE_4 DATE NOT NULL DEFAULT 1
);
COMMENT ON table TYPETEST is 'タイプテスト';
COMMENT ON column TYPETEST.TYPE_1 is 'タイプ１';
COMMENT ON column TYPETEST.TYPE_2 is 'タイプ２';
COMMENT ON column TYPETEST.TYPE_3 is 'タイプ３';
COMMENT ON column TYPETEST.TYPE_4 is 'タイプ４';
