CREATE TABLE PUBLIC.B_TABLE (
  B_ID BIGINT NOT NULL,
  C_ID BIGINT,
  D_ID BIGINT,
  NAME VARCHAR(100),
  TEST1 VARCHAR(100),
  TEST2 VARCHAR(500),
  TEST3 VARCHAR(500),
  PRIMARY KEY (B_ID)
);
COMMENT ON table PUBLIC.B_TABLE is 'B_TABLE';
COMMENT ON column PUBLIC.B_TABLE.B_ID is 'B_ID';
COMMENT ON column PUBLIC.B_TABLE.C_ID is 'C_ID';
COMMENT ON column PUBLIC.B_TABLE.D_ID is 'D_ID';
COMMENT ON column PUBLIC.B_TABLE.NAME is 'NAME';
COMMENT ON column PUBLIC.B_TABLE.TEST1 is 'TEST1';
COMMENT ON column PUBLIC.B_TABLE.TEST2 is 'TEST2';
COMMENT ON column PUBLIC.B_TABLE.TEST3 is 'TEST3';
CREATE SEQUENCE PUBLIC.B_ID_SEQ increment by 1 start with 1;
